import Head from "next/head";

const Index = () => {
  return (
    <>
      <Head>
        <title>App: Page 2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <p>page 2</p>
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p>{" "}
        <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>overflowing</p> <p>end.</p>
      </>
    </>
  );
};

export default Index;
